<?php

/**
 * @file
 * Contains custom_mail.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_mail().
 */
function task_module_mail($key, &$message, $params)
{
  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
    case 'create_page':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Page created: @title', array('@title' => $params['node_title']), $options);
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function task_module_entity_insert(Drupal\Core\Entity\EntityInterface $entity)
{

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'page')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'task_module';
  $key = 'create_page';
  $to = \Drupal::currentUser()->getEmail();
  $params['message'] = $entity->get('body')->value;
  $params['node_title'] = $entity->label();
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = true;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== true) {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
    //drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  } else {

    \Drupal::messenger()->addMessage(t('Your message has been sen'), 'status');
    // drupal_set_message(t('Your message has been sent.'));
  }
}
